"""Build and run the complete server-side Rockbase orchestration pipeline."""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Sequence

from .rockbase_orchestrator import Stage, run_pipeline
from .run_mail_loop import build_mail_loop_stages


REPO_ROOT = Path(__file__).resolve().parents[1]
S1_API = REPO_ROOT / "skills/S1-inbox-enrichment/scripts/api"
S2_RUNNER = REPO_ROOT / (
    "skills/S1-inbox-kol-fuzzy-discovery-youtube-skill/src/"
    "youtube_kol_discovery/pipelines/run_s2_mail1_fill.py"
)
S5_SCRIPT = REPO_ROOT / "skills/S5-ag-ocr-sync/scripts/ag_ocr_sync.py"


def _script_command(script: Path, *args: object) -> tuple[str, ...]:
    return (sys.executable, str(script), *(str(arg) for arg in args))


def _s1_paths(csv_path: Path, date: str, platform: str) -> tuple[Path, Path]:
    prefix = f"{platform}_scrapecreators_batch"
    workbench = csv_path.resolve().parents[2] / "workbench" / date
    return workbench / f"{prefix}_*_raw.json", workbench / f"{prefix}_*_summary.json"


def build_full_pipeline_stages(
    *,
    csv_path: Path,
    config: Path,
    state_path: Path,
    fetch_out: Path,
    date: str,
    platform: str = "youtube",
    s1_rows: str = "",
    with_s1: bool = False,
    s1_apply: bool = False,
    s2_write: bool = False,
    with_s5: bool = False,
    image_dir: Path | None = None,
    s5_engine: str = "auto",
    s5_write: bool = False,
    execute_send: bool = False,
    execute_sync: bool = False,
    pause_file: Path | None = None,
    approval_files: dict[str, Path] | None = None,
    console_run: bool = False,
) -> list[Stage]:
    if platform != "youtube":
        raise ValueError("full pipeline currently supports only youtube S2 generation")
    stages: list[Stage] = []
    s1_raw_glob, _ = _s1_paths(csv_path, date, platform)
    if with_s1:
        export_script = S1_API / f"{platform}_scrapecreators_s1_export.py"
        apply_script = S1_API / f"{platform}_scrapecreators_s1_apply.py"
        if not export_script.exists() or not apply_script.exists():
            raise ValueError(f"unsupported S1 platform: {platform}")
        export_args = ["--csv", csv_path, "--date", date]
        if s1_rows:
            export_args.extend(["--rows", s1_rows])
        stages.append(Stage("s1_export", _script_command(export_script, *export_args),
                            artifacts=(s1_raw_glob,)))
        # The export timestamp is generated by the script; the glob is checked
        # by the runner's artifact matcher after the command completes.
        apply_args = ["--csv", csv_path, "--json", s1_raw_glob,
                      "--mode", "apply" if s1_apply else "preview", "--date", date]
        stages.append(Stage("s1_apply", _script_command(apply_script, *apply_args)))

    s2_args = ["--run-date", date, "--input-csv", str(csv_path)]
    if not s2_write:
        s2_args.append("--dry-run")
    s2_artifact = csv_path.parent / "workbench" / date / "YouTube" / \
        f"youtube_kol_S2_mail1_fill_runlog_{date}.json"
    stages.append(Stage("s2_mail1_generate", _script_command(S2_RUNNER, *s2_args),
                        artifacts=(s2_artifact,)))
    stages.extend(build_mail_loop_stages(
        batch_csv=csv_path,
        config=config,
        master=csv_path,
        state_path=state_path,
        fetch_out=fetch_out,
        execute_send=execute_send,
        execute_sync=execute_sync,
    ))

    if with_s5:
        if image_dir is None:
            raise ValueError("image_dir is required when with_s5 is enabled")
        s5_args = ["--image-dir", image_dir, "--csv-path", csv_path,
                   "--ocr-engine", s5_engine]
        if not s5_write:
            s5_args.append("--dry-run")
        s5_report = image_dir / "ocr_results_*.json"
        stages.append(Stage("s5_ocr", _script_command(S5_SCRIPT, *s5_args),
                            artifacts=(s5_report,)))
    return stages


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=None,
                        help="master CSV; defaults to $ROCKBASE_MASTER_CSV")
    parser.add_argument("--config", type=Path, default=None,
                        help="mailkit config; defaults to $ROCKBASE_MAILKIT_CONFIG")
    parser.add_argument("--state", type=Path, required=True)
    parser.add_argument("--fetch-out", type=Path, default=None,
                        help="reply fetch output; defaults to $ROCKBASE_PIPELINE_FETCH_OUT "
                             "or <cwd>/workbench/replies-current")
    parser.add_argument("--date", default=datetime.now().strftime("%Y-%m-%d"))
    parser.add_argument("--platform", choices=["youtube", "instagram", "tiktok"], default="youtube")
    parser.add_argument("--with-s1", action="store_true")
    parser.add_argument("--s1-rows", default="")
    parser.add_argument("--s1-apply", action="store_true")
    parser.add_argument("--s2-write", action="store_true",
                        help="allow S2 to write Mail1 fields; default is audit-only")
    parser.add_argument("--with-s5", action="store_true")
    parser.add_argument("--image-dir", type=Path)
    parser.add_argument("--s5-engine", choices=["auto", "vision", "tesseract", "llm"], default="auto")
    parser.add_argument("--s5-write", action="store_true")
    parser.add_argument("--execute-send", action="store_true")
    parser.add_argument("--execute-sync", action="store_true")
    parser.add_argument("--console-run", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--run-id", default=None,
                        help="stable run identifier recorded in the state file "
                             "(the console workbench passes the id it allocated)")
    parser.add_argument("--console-pause-file", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--console-send-approval", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--console-sync-approval", type=Path, help=argparse.SUPPRESS)
    parser.add_argument("--retries", type=int, default=0)
    parser.add_argument("--plan", action="store_true")
    args = parser.parse_args(argv)
    approval_files = {}
    if args.console_send_approval:
        approval_files["send"] = args.console_send_approval
    if args.console_sync_approval:
        approval_files["sync"] = args.console_sync_approval

    def _resolve(value: Path | None, env_name: str, flag: str) -> Path:
        """Resolve a required input: flag first, then env, else fail clearly."""
        if value is not None:
            path = value
        else:
            env_value = os.environ.get(env_name)
            if not env_value:
                raise SystemExit(
                    f"error: {flag} is required (pass --{flag.lstrip('-')} or set ${env_name})")
            path = Path(env_value)
        if not path.exists():
            raise SystemExit(f"error: {flag} path not found: {path}")
        return path

    csv_path = _resolve(args.csv, "ROCKBASE_MASTER_CSV", "--csv")
    config_path = _resolve(args.config, "ROCKBASE_MAILKIT_CONFIG", "--config")

    if args.fetch_out is not None:
        fetch_out = args.fetch_out
    else:
        fetch_env = os.environ.get("ROCKBASE_PIPELINE_FETCH_OUT")
        fetch_out = Path(fetch_env) if fetch_env else Path.cwd() / "workbench" / "replies-current"

    # S1/S2 stage scripts locate the business project root from the process
    # cwd and require workbench/ next to the master CSV. Anchor every input
    # absolutely, then run from the CSV directory so console-spawned and
    # entrypoint-spawned runs behave identically.
    csv_path = csv_path.resolve()
    config_path = config_path.resolve()
    args.state = args.state.resolve()
    if not fetch_out.is_absolute():
        fetch_out = (Path.cwd() / fetch_out).resolve()
    os.chdir(csv_path.parent)
    if not args.plan:
        (csv_path.parent / "workbench").mkdir(exist_ok=True)

    stages = build_full_pipeline_stages(
        csv_path=csv_path, config=config_path, state_path=args.state,
        fetch_out=fetch_out, date=args.date, platform=args.platform,
        s1_rows=args.s1_rows, with_s1=args.with_s1, s1_apply=args.s1_apply,
        s2_write=args.s2_write, with_s5=args.with_s5, image_dir=args.image_dir, s5_engine=args.s5_engine,
        s5_write=args.s5_write, execute_send=args.execute_send,
        execute_sync=args.execute_sync,
        pause_file=args.console_pause_file, approval_files=approval_files,
        console_run=args.console_run,
    )
    return run_pipeline(stages, state_path=args.state, plan_only=args.plan, retries=args.retries,
                        pause_file=args.console_pause_file, approval_files=approval_files,
                        console_run=args.console_run,
                        run_id=args.run_id or os.environ.get("ROCKBASE_RUN_ID"))


if __name__ == "__main__":
    raise SystemExit(main())
